defaults:
  - _self_
  - model: random_forest

data:
  input_file: "/home/ta45woj/PolyMetriX/data/Polymer_Tg_featurizers.csv"
  polymer_column: "PSMILES"
  label_column: "Exp_Tg(K)"
  test_size: 0.1
  validation_size: 0.15
  random_state: 40

featurizer:
  type: "default"

optimization:
  n_trials: 1

experiment:
  seeds: [42, 43]