defaults:
  - _self_
  - model: random_forest

data:
  input_file: "/home/ta45woj/PolyMetriX/data/Polymer_Tg_featurizers.csv"
  polymer_column: "PSMILES"
  label_column: "Exp_Tg(K)"
  test_size: 0.1
  validation_size: 0.15
  random_state: 40

featurizer:
  type: "default"
  use_default: false  # Set to false to use only custom featurizers
  custom_featurizers:
    - molecular_weight_fullpolymerfeaturizer
    - sp3_carbon_count_fullpolymerfeaturizer
    - sp2_carbon_count_fullpolymerfeaturizer
    - max_estate_index_fullpolymerfeaturizer
    - smr_vsa5_fullpolymerfeaturizer
    - fp_density_morgan1_fullpolymerfeaturizer

optimization:
  n_trials: 1

experiment:
  seeds: [42, 43, 44]